### ISSUE TITLE
Data not refreshed upon extending loans with services

### ISSUE THREAD

**Issue by myTselection** [myTselection/bibliotheek_be#9]
The services to extend loans are working, but the result is no immediately visible.
Currently the sensors have a throttle configured to only fetch updates from the bibliotheek.be website every hour. So even when forcing a sensor update, only the cached data is returned and it may take up to one hour before the loan extension will become visible.

For now, I don't have an immediate solution to this. Not sure how I can call the forceupdate method on the sensor from within the services.

**Comment by myTselection** [comment]
as workaround:, reload can be triggered for now, eg using 
```
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id:
        - sensor.bibliotheek_be_bib_name
```
